### ISSUE TITLE
[BACKEND] [WEBHOOK] Add logic for new booking on successful checkout

### ISSUE THREAD

**Issue by bcho892** [UoaWDCC/uasc-web#133]
**WARNING**: VERY HARD

**Is your feature request related to a problem? Please describe.**
Blocked by #131, linked to #186 

After a member books a lodge, the webhook will be hit by a ~~[checkout.session.completed](https://docs.stripe.com/api/events/types#event_types-checkout.session.completed), and we need to handle this.~~ [payment_intent.succeeded](https://docs.stripe.com/payments/payment-methods#webhooks) webhook event

**Describe the solution you'd like**
- Use #237 to get the checkout session
- Need to check the `client_reference_id` (which will give the user's firebase uid)
- Check metadata for the appropriate key (to check that the payment was for lodge booking) see #132 
- Update firestore 
   - reduce availability for the slot - based on a document that uses a stripe id
   - deactivate product on stripe if its 0
   - Add booking for the user
- Send emails (optional, need client clarification)

**Additional context**
Any business logic failures should not give a `200` response

**BEFORE MERGING**
- [ ] Integration test written for services
- [ ] Code generation run (*hint*: `yarn workspace server tsoa spec-and-routes`)
- [ ] Appropriate mocks created where possible
- [ ] PR Reviewed (For non-trivial changes)
- [ ] Changes tested after rebasing on master or merging in master (*hint*: `git fetch origin master:master`, then `git rebase master` or `git merge master`)
- [ ] All required PR checks passing

**Comment by 8cw** [comment]
`checkout.session.completed` will be hit once the user has completed the checkout, but this does not guarantee that they have paid. Do we want to only confirm the booking once they have actually paid? In other words, perform all this logic on a [`payment_intent.succeeded`](https://docs.stripe.com/payments/payment-methods#webhooks) webhook event?

Some things to think about:
- we will need to check with the client if we are going to have issues where a bunch of people book all at once. I'm not sure how realistic this scenario is, probably not very -- but something to check
- what happens if we get a `checkout.session.completed`, but then the payment later fails?
- should we "reserve" the hut booking _before_ a checkout session begins for some time, to allow the user to pay?
- if so, how long should we wait between creating a hut booking session, and needing payment done by?
- what happens if the users reserve expires, but then they pay, and there is no hut bookings available?
  - probably need some admin intervention here

these are all sort of things that need to get "thought about". the simplest path is to ignore any race condition issues in the checkout process, and use either one of the `checkout.session.completed` or `payment_intent.succeeded` events to handle payment. perhaps we tackle the rest in future PRs.

if we go with `checkout.session.completed`, should we assume that the payment will eventually succeed?
